// Serena Chan
// Systems Level Programming
// 11/17/2020
// Work 11: /dev[ise a]/random plan

#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <errno.h>

// generates and returns a random number by reading in correct number of bytes from /dev/random
int rand_number(){
    int rand_num[1];
    
    int file = open("/dev/random", O_RDONLY); // opens /dev/random
    if (file == -1){
        printf("Error: %s\n", strerror(errno));
    }
    
    int err = read(file, rand_num, sizeof(rand_num));
    if (err == -1){
        printf("Error: %s\n", strerror(errno));
    }
            
    close(file);
    return rand_num[0];
}

int main(){
    // populates an array with 10 random numbers generated by random function
    int arr[10];
    
    printf("Generating random numbers:\n");

    int i;
    for (i = 0; i < 10; i++){
        arr[i] = rand_number();
        printf("random %d: %d \n", i, arr[i]); // prints out the contents of array
        }
    
    int output = open("./out", O_RDWR);
    if (output == -1){
        printf("Error: %s\n", strerror(errno));
    }
            
    // writes the array to a file
    printf("\nWriting numbers to file...\n");
    int diff;
    diff = write(output, arr, sizeof(arr));
    

    // reads that file into a different array
    printf("\nReading numbers from file...\n");
    int rd[10];
    read(output, rd, sizeof(rd));

    // prints out the contents of the second array to verify the random numbers are the same from step 1
    printf("\nVerification that written values were the same:\n");
    for (i = 0; i < 10; i++){
        printf("random %d: %d \n", i, arr[i]);
    }
}
